SELECT 
	II.MONITEMINSTANCESEQ
	,II.MONITOROBJECT
	,OBNW.DISPLAY_NAME
	,COALESCE(RTP.MONITORVALUE, '0') AS USE_YN
	,CA.*
FROM TB_ONEBOX_NW OBNW
LEFT OUTER JOIN TB_MONITEMINSTANCE II ON (II.SERVERSEQ=OBNW.SERVERSEQ AND II.MONITOROBJECT = OBNW.NAME)
LEFT OUTER JOIN TB_MONTARGETCATALOG TC ON (II.MONTARGETCATSEQ=TC.MONTARGETCATSEQ)
LEFT OUTER JOIN TB_MONGROUPCATALOG GC ON (II.MONGROUPCATSEQ=GC.MONGROUPCATSEQ )
LEFT OUTER JOIN TB_MONITEMCATALOG IC ON (II.MONITEMCATSEQ=IC.MONITEMCATSEQ)
LEFT OUTER JOIN TB_CURALARM CA ON (CA.MONITEMINSTANCESEQ=II.MONITEMINSTANCESEQ AND CA.RESOLVE_DTTM IS NULL )
LEFT OUTER JOIN TB_REALTIMEPERF RTP ON (RTP.MONITEMINSTANCESEQ = II.MONITEMINSTANCESEQ AND RTP.SERVERSEQ=OBNW.SERVERSEQ AND RTP.MONITOREDYN = 'y' )
WHERE OBNW.SERVERSEQ = 719
	AND II.DELETE_DTTM IS NULL 
	AND TC.TARGETCODE = 'os' 
	AND GC.GROUPNAME = 'net' 
	AND IC.MONITORTYPE = 'Status'
ORDER BY II.MONITOROBJECT

